package com.salami.dragon.engine.event;

public enum EventType {
    // APP
    APPLICATION_START, APPLICATION_STOP, APPLICATION_INIT, APPLICATION_TICK,

    // WINDOW
    WINDOW_OPEN, WINDOW_CLOSE, WINDOW_RESIZE, WINDOW_MOVE, WINDOW_LOST_FOCUS, WINDOW_FOCUS, WINDOW_MAXIMIZE, WINDOW_UN_MAXIMIZE,

    // KEYBOARD
    KEY_PRESS, KEY_RELEASE,

    // MOUSE
    MOUSE_BUTTON_PRESS, MOUSE_BUTTON_RELEASE, MOUSE_MOVE, MOUSE_SCROLL,

    // AUDIO
    AUDIO_INIT, AUDIO_REGISTER_BUFFER, AUDIO_UNREGISTER_BUFFER, AUDIO_REGISTER_SOURCE, AUDIO_UNREGISTER_SOURCE,
    AUDIO_REGISTER_LISTERER,

    // AUDIO SOURCE
    AUDIO_SOURCE_INIT, AUDIO_SOURCE_PLAY, AUDIO_SOURCE_STOP, AUDIO_SOURCE_PAUSE, AUDIO_SOURCE_CLEANUP,
    AUDIO_SOURCE_NEW_AUDIO, AUDIO_SOURCE_NEW_POSITION, AUDIO_SOURCE_NEW_VELOCITY, AUDIO_SOURCE_NEW_GAIN,

    // AUDIO LISTENER
    AUDIO_LISTENER_INIT, AUDIO_LISTENER_NEW_POSITION, AUDIO_LISTENER_NEW_VELOCITY, AUDIO_LISTENER_NEW_ORIENTATION
}
